### ISSUE TITLE
interval tree

### ISSUE THREAD

**Issue by brentp** [Nycto/RBTreeNim#3]
hi, nice library!
it seems, from quick look that it might be possible to use this as an interval tree with the correct comparator, is that correct? Something like:

```Nim
import rbtree

type Interval = object
    start, stop: int

proc cmp*( a, b: Interval ): int =
  if a.stop < b.start: return -1
  if b.stop < a.start: return 1
  return 0

var tree = newRBTree[Interval, Interval]()
```

does this look right?

**Comment by Nycto** [comment]
I don't think this will work. The goal of an interval tree is to supply a point and determine all the intervals that overlap that tree, right? The `cmp` function will give you a well sorted tree, but there still isn't any way to do that lookup.

The most you would get from this is a list of intervals you can traverse in order.

**Comment by brentp** [comment]
understood. guess I'll be forced to implement an interval tree at some point.
